#!/bin/bash
# param1=alias
# param2=tag
# param3=seuil
# param4=designation
# param5=destinataire
# param6=copieCC
#
# ./warning_level chimiques _70LT01 95 "Niveau bas des cuves TUG" stephane.leicht@foxinfo.fr stephane.jeanne@gmail.com
#
MYPATH="/var/alarme/"
TAG=$2
DESTINATAIRE=$5
CC=$6
FICHIER=$MYPATH$TAG.$3
VALEUR=`/usr/local/bin/readtag -a $1 $TAG`
if [[ $VALEUR == ERR ]]
then
  echo "Erreur de lecture de readtag"
  exit 1
else
  TEST=$(echo "$VALEUR>$3"|bc)
  if [ "$TEST" -eq 1 ]
  then
  	if [ -f "$FICHIER" ]
  	then
  		rm $FICHIER
  	fi
  else
  	if [ ! -f "$FICHIER" ]
  	then
  		BODY="Mail automatique du serveur $HOSTNAME :\nAlarme sur $TAG\n$4\nValeur actuelle : $VALEUR\nSeuil : $3\n"
  		printf "$BODY"
  		touch $FICHIER
		if [ -n "$CC" ]
		then
  			printf "$BODY" | mail -s "Alarme" $DESTINATAIRE -c $CC 
		else
			printf "$BODY" | mail -s "Alarme" $DESTINATAIRE
		fi
  	fi
  fi
fi
